app_name: example
indexer:
  build:
    data_dir: data/${app_name}/corpus
    index_dir: persist_dir/${app_name}/index
data_builder:
  generate_synthetic_query:
    index_dir: ${indexer.build.index_dir} 
    output_path: data/${app_name}/synthetic_data/synthetic_queries.json
    random_seed: 0
    from_num_nodes: 10
  build_from_annotated_retrieval_data:
    annotated_data_path: data/${app_name}/annotated_data/annotated_example.xlsx
    index_dir: ${indexer.build.index_dir} 
    output_path: data/${app_name}/annotated_data/annotated_data.json
    question_field: question
    annotated_field: annotated_reference
retriever:
  evaluate:
    test_data_path: ${data_builder.generate_synthetic_query.output_path}
    index_dir: ${indexer.build.index_dir}
    metrics: 
      - "mrr"
      - "hit_rate"
synthesizer:
  render:
    index_dir: ${indexer.build.index_dir}
    app_description: ${app_name}
