app_name: example
indexer:
  build:
    data_dir: data/${app_name}/corpus
    index_dir: persist_dir/${app_name}/index
    pre_processor_cfg:
      pre_processor_type: azure
      azure_pre_processor_cfg:
        file_type: Guidance
        paragraph_process_cfg:
          polygon_group: true
          chunk_size: 512
          sentence_splitter_cfg:
            chunk_size: 512
            chunk_overlap: 20          
        table_process_cfg:
          include_table: true
          by_token: true
          token_limit: 3000
      sentence_splitter_cfg:
        chunk_size: 512
        chunk_overlap: 20
      file_metadata: 
    post_processor_cfg: 
      enable_node_expander: true
      parent_metadata_field: document_name
data_builder:
  generate_synthetic_query:
    index_dir: ${indexer.build.index_dir}
    from_parent_node: true
    from_num_sources: 2
    prompt_template_path: data/${app_name}/synthetic_data/qa_gen_tmpl.txt
    random_seed: 0
    num_questions_per_chunk: 2
    openai_model_name: gpt-4-1106-preview
    json_output_path: data/${app_name}/synthetic_data/synthetic_queries.json
    excel_output_path: data/${app_name}/synthetic_data/synthetic_queries.xlsx
    metadata_field_to_save: document_name
  build_from_annotated_retrieval_data:
    annotated_data_path: data/${app_name}/annotated_data/annotated_example.xlsx
    index_dir: ${indexer.build.index_dir} 
    output_path: data/${app_name}/annotated_data/annotated_data.json
    question_field: question
    annotated_field: annotated_reference
retriever:
  evaluate:
    test_data_path: ${data_builder.generate_synthetic_query.output_path}
    index_dir: ${indexer.build.index_dir}
    metrics: 
      - "mrr"
      - "hit_rate"
synthesizer:
  app:
    index_dir: ${indexer.build.index_dir}
    app_description: ${app_name}
    enable_hyde: true
    show_retrieved_nodes: true
    reference_url: false
    enable_node_expander: true
    openai_model_name: gpt-3.5-turbo-1106
    include_historical_messages: true
    document_bucket_name:
    citation_cfg:
      citation_chunk_size: 512
      citation_qa_template_path: data/${app_name}/cite/citation_qa_template.txt
      similarity_top_k: 3
      google_search_topk: 3     
    port: 3000 
  batch_generate:
    index_dir: ${indexer.build.index_dir}
    enable_hyde: true
    enable_node_expander: true
    openai_model_name: gpt-3.5-turbo-1106
    citation_cfg:
      citation_chunk_size: 512
      citation_qa_template_path: data/${app_name}/cite/citation_qa_templat.txt
      similarity_top_k: 3
      google_search_topk: 3
    excel_input_path: ${data_builder.generate_synthetic_query.excel_output_path}
    output_dir: data/${app_name}/output
    query_field_name:
    max_num_queries:
    start_query_idx: 0
