app_name: example
indexer:
  build:
    data_dir: data/${app_name}/corpus
    index_dir: persist_dir/${app_name}/index
    data_processor: azure
    node_parser:
      type: sentence_splitter
      args:
        sentence_splitter:
          chunk_size: 512
          chunk_overlap: 20
data_builder:
  generate_synthetic_query:
    index_dir: ${indexer.build.index_dir} 
    prompt_template_path: data/${app_name}/synthetic_data/generate_synthetic_query_prompt_template.txt
    output_path: data/${app_name}/synthetic_data/synthetic_queries.json
    random_seed: 0
    from_num_nodes: 2
    num_questions_per_chunk: 2
  build_from_annotated_retrieval_data:
    annotated_data_path: data/${app_name}/annotated_data/annotated_example.xlsx
    index_dir: ${indexer.build.index_dir} 
    output_path: data/${app_name}/annotated_data/annotated_data.json
    question_field: question
    annotated_field: annotated_reference
retriever:
  evaluate:
    test_data_path: ${data_builder.generate_synthetic_query.output_path}
    index_dir: ${indexer.build.index_dir}
    metrics: 
      - "mrr"
      - "hit_rate"
synthesizer:
  render:
    index_dir: ${indexer.build.index_dir}
    app_description: ${app_name}
    citation_cfg:
      enable_cite: true
      citation_chunk_size: 512
      similarity_top_k: 3
